package org.bsc.confluence;

import java.net.MalformedURLException;

/**
 *
 * @author Sorrentino
 *
 */
public class ConfluenceUtils {

    /**
     *
     * @param value
     * @return
     */
    public static String decode(String value) {
        if (null == value) {
            return value;
        }
        final String result = value
                .replace("{", "\\{")
                .replace("}", "\\}")
                .replaceAll("</?[Pp][Rr][Ee]>", "{noformat}")
                .replaceAll("<[Cc][Oo][Dd][Ee]>", "{{")
                .replaceAll("</[Cc][Oo][Dd][Ee]>", "}}")
                .replaceAll("</?[Bb]>", "*")
                .replaceAll("<[Bb][Rr]/?>", "\\\\")
                .replaceAll("<[Hh][Rr]/?>", "----")
                .replaceAll("<[Pp]>", "\n\n")
                .replaceAll("</[Pp]>", "");
        return ConfluenceHtmlListUtils.replaceHtmlList(result);
    }

    /**
     *
     * @param value
     * @return
     */
    public static String encodeAnchor(String value) {

        if (null == value) {
            return null;
        }

        String v = decode(value);

        try {
            new java.net.URL(v);

            return v;

        } catch (MalformedURLException e) {

            return v.replace(':', '_');

        }

    }

    /**
     *
     * @return ads banner
     */
    public static String getBannerWiki() {

        final StringBuilder wiki = new StringBuilder()
                .append("{info:title=").append("Generated page").append('}')
                .append("this page has been generated by plugin: ")
                .append("[org.bsc.maven:maven-confluence-reporting-plugin|https://github.com/bsorrentino/maven-confluence-plugin]")
                .append("{info}")
                .append('\n');

        return wiki.toString();
    }

}
