package org.bsc.maven.plugin.confluence;

import org.apache.maven.plugin.logging.Log;
import static org.bsc.maven.plugin.confluence.ConfluenceUtils.decode;

import java.io.File;
import java.io.IOException;
import java.io.StringWriter;
import java.io.Writer;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import org.apache.maven.plugin.descriptor.MojoDescriptor;
import org.apache.maven.plugin.descriptor.Parameter;
import org.apache.maven.plugin.descriptor.PluginDescriptor;
import org.apache.maven.tools.plugin.generator.Generator;
import org.codehaus.plexus.util.StringUtils;
import org.codehaus.swizzle.confluence.Confluence;
import org.codehaus.swizzle.confluence.Page;
//import org.codehaus.swizzle.confluence.PageSummary;

/**
 * 
 * @author Sorrentino
 *
 */
@SuppressWarnings("unchecked")
public class PluginConfluenceDocGenerator implements Generator {

	private Confluence confluence;
	private Page parentPage;
	private final Log log;
	/**
	 * 
	 * @param space
	 */
	public PluginConfluenceDocGenerator( Confluence confluence, Page parentPage, Log log ) {
		this.confluence = confluence;
		this.parentPage = parentPage;
                this.log = log;
	
	}

	
	/**
	 * 
	 */
	public void execute( File destinationDirectory, PluginDescriptor pluginDescriptor ) throws IOException {
	    	

        try {
			processMojoDescriptors(pluginDescriptor);
		} catch (Exception e) {
			
			throw new IOException( e.getMessage() );
		}
    }
	
	/**
	 * 
	 * @param mojoDescriptor
	 * @param destinationDirectory
	 * @throws IOException
	 */
    protected void processMojoDescriptors( PluginDescriptor pluginDescriptor ) throws Exception
    {
    	List<MojoDescriptor> mojos = pluginDescriptor.getMojos();

    	if( mojos==null ) {
            log.warn( "no mojos found [pluginDescriptor.getMojos()]");
            return ;
        }
    	
    	String title = pluginDescriptor.getArtifactId() + "-" + pluginDescriptor.getVersion();
    	
    	Page page = ConfluenceUtils.getOrCreatePage(confluence, parentPage, title);
    	    	
        StringWriter writer = new StringWriter(100*1024);

        writeSummary( writer, pluginDescriptor, mojos );

        writer.flush();
        
        page.setContent(writer.toString());
        
        confluence.storePage(page);

    }

	/**
	 * 
	 * @param writer
	 * @param mojoDescriptor
	 */
    private void writeSummary( Writer writer, PluginDescriptor pluginDescriptor, List<MojoDescriptor> mojos ) {
    	
    	ConfluenceWikiWriter w = new ConfluenceWikiWriter( writer );
    	
    	w.printInfo( "auto generated page", 
    			"this page has been generated by plugin : " + 
    			"org.bsc.maven:maven-confluence-reporting-plugin-plugin" );
    	
    	w.printBiggerHeading( "Description");
    	
    	String description = pluginDescriptor.getDescription();
    	
    	if( null!=description ) {
    		w.println( description );
    	}

    	w.printNewParagraph();
    	    	
    	w.printBiggerHeading( "Plugin Goals");
    	    	
    	for ( MojoDescriptor descriptor : mojos )
        {
    		w.appendBullet().printLinkToAnchor(descriptor.getGoal(), descriptor.getFullGoalName());
        }
    	
    	w.printNewParagraph();
    	
    	for ( MojoDescriptor descriptor : mojos )
        {
    		writeBody(w, descriptor);
        }

    }

    /**
     * 
     * @param writer
     * @param mojoDescriptor
     */
    private void writeBody( ConfluenceWikiWriter w, MojoDescriptor mojoDescriptor )
    {
        
    	w.appendBiggerHeading()
    		.appendAnchor(mojoDescriptor.getGoal(), mojoDescriptor.getFullGoalName())
    		.println();
    	
        String description = ( mojoDescriptor.getDescription() != null ) ?
        								mojoDescriptor.getDescription() :
        								"No description.";
        
        w.printQuote(description);

    	w.printNewParagraph();
        
        writeGoalAttributes( mojoDescriptor, w );

    	w.printNewParagraph();
        
        writeGoalParameterTable( mojoDescriptor, w );

    }

    /**
     * 
     * @param mojoDescriptor
     * @param w
     */
    private void writeGoalAttributes( MojoDescriptor mojoDescriptor, ConfluenceWikiWriter w )
    {
        w.printBigHeading("Mojo Attributes");
        
        String value = mojoDescriptor.getDeprecated();
        
        if ( StringUtils.isNotEmpty( value ) ) {
        	w.printBullet("This plugin goal has been deprecated: " + value);
        }

        if ( mojoDescriptor.isProjectRequired() ) {
        	w.printBullet("Requires a Maven 2.0 project to execute.");
        }

        if ( mojoDescriptor.isAggregator() ) {
            w.printBullet( "Executes as an aggregator plugin." );
        }

        if ( mojoDescriptor.isDirectInvocationOnly() ) {
            w.printBullet( "Executes by direct invocation only." );
        }

        value = mojoDescriptor.isDependencyResolutionRequired();
        
        if ( StringUtils.isNotEmpty( value ) ) {
            w.printBullet( "Requires dependency resolution of artifacts in scope: <code>" + value + "</code>" );
        }

        value = mojoDescriptor.getSince();
        if ( StringUtils.isNotEmpty( value ) ) {
            w.printBullet( "Since version: <code>" + value + "</code>" );
        }

        value = mojoDescriptor.getPhase();
        if ( StringUtils.isNotEmpty( value ) )
        {
            w.printBullet( "Automatically executes within the lifecycle phase: <code>" + value + "</code>" );
        }

        value = mojoDescriptor.getExecutePhase();
        if ( StringUtils.isNotEmpty( value ) )
        {
            w.printBullet(
                "Invokes the execution of the lifecycle phase <code>" + value + "</code> prior to executing itself." );
        }

        value = mojoDescriptor.getExecuteGoal();
        if ( StringUtils.isNotEmpty( value ) )
        {
            w.printBullet(
                "Invokes the execution of this plugin's goal <code>" + value + "</code> prior to executing itself." );
        }

        value = mojoDescriptor.getExecuteLifecycle();
        if ( StringUtils.isNotEmpty( value ) )
        {
            w.printBullet( "Executes in its own lifecycle: <code>" + value + "</code>" );
        }

        if ( mojoDescriptor.isOnlineRequired() )
        {
            w.printBullet( "Requires that mvn runs in online mode." );
        }

        if ( !mojoDescriptor.isInheritedByDefault() )
        {
            w.printBullet( "Is NOT inherited by default in multi-project builds." );
        }
    }

    /**
     * 
     * @param mojoDescriptor
     * @param w
     */
    private void writeGoalParameterTable( MojoDescriptor mojoDescriptor, ConfluenceWikiWriter w )
    {
        List<Parameter> parameterList = mojoDescriptor.getParameters();

        //remove components and read-only parameters
        List<Parameter> list = filterParameters( parameterList );

        if ( list != null && list.size() > 0 )
        {
            writeParameterSummary( list, w );

            writeParameterDetails( list, w );
        }
    }

    /**
     * 
     * @param parameterList
     * @return
     */
    private List<Parameter> filterParameters( List<Parameter> parameterList )
    {
        List<Parameter> filtered = new ArrayList<Parameter>();

        if ( parameterList != null )
        {
            for ( Parameter parameter : parameterList ) {

                if ( parameter.isEditable() )
                {
                    String expression = parameter.getExpression();

                    if ( expression == null || !expression.startsWith( "${component." ) )
                    {
                        filtered.add( parameter );
                    }
                }
            }
        }

        return filtered;
    }

    /**
     * 
     * @param parameterList
     * @param w
     */
    private void writeParameterDetails( List<Parameter> parameterList, ConfluenceWikiWriter w )
    {
    	w.printBigHeading("Parameter Details");
    	
    	w.printNewParagraph();

        for ( Parameter parameter : parameterList )
        {

        	w.printNormalHeading( parameter.getName() );
        	

            String description = parameter.getDescription();
            if ( StringUtils.isEmpty( description ) )
            {
                description = "No Description.";
            }
            
            w.println( decode(description) );
            
            
            writeDetail( "Deprecated", parameter.getDeprecated(), w );

            writeDetail( "Type", parameter.getType(), w );

            writeDetail( "Since", parameter.getSince(), w );

            if ( parameter.isRequired() )
            {
                writeDetail( "Required", "Yes", w );
            }
            else
            {
                writeDetail( "Required", "No", w );
            }

            writeDetail( "Expression", parameter.getExpression(), w );

            writeDetail( "Default", parameter.getDefaultValue(), w );

        }

    }

    private void writeDetail( String param, String value, ConfluenceWikiWriter w )
    {
        if ( StringUtils.isNotEmpty( value ) )
        {
        	w.printf("|%s|%s|\n", decode(param), decode(value) );
        }
    }

    /**
     * 
     * @param parameterList
     * @param w
     */
    private void writeParameterSummary( List<Parameter> parameterList, ConfluenceWikiWriter w )
    {
        List requiredParams = getParametersByRequired( true, parameterList );
        if ( requiredParams.size() > 0 )
        {
            writeParameterList( "Required Parameters", requiredParams, w );
        }

        List optionalParams = getParametersByRequired( false, parameterList );
        if ( optionalParams.size() > 0 )
        {
            writeParameterList( "Optional Parameters", optionalParams, w );
        }
    }

    /**
     * 
     * @param title
     * @param parameterList
     * @param w
     */
    private void writeParameterList( String title, List<Parameter> parameterList, ConfluenceWikiWriter w )
    {
    	w.printBigHeading(title);
    	
    	w.printNewParagraph();
    	
    	w.printf( "||%s||%s||%s||\n", "Name", "Type", "Description");

        for ( Parameter parameter : parameterList ) {

            int index = parameter.getType().lastIndexOf( "." );

            w.print( '|' );
			
            w.print( parameter.getName() );

            w.print( '|' );
			
            w.print( parameter.getType().substring( index + 1 ) );
			
            w.print( '|' );

            String description = parameter.getDescription();
            if ( StringUtils.isEmpty( description ) )
            {
                description = "No description.";
            }
            if ( StringUtils.isNotEmpty( parameter.getDeprecated() ) )
            {
                description = "Deprecated. " + description;
            }
            
            w.print( decode(description.replace( '\n' , ' ')) );

            if ( StringUtils.isNotEmpty( parameter.getDefaultValue() ) )
            {
                w.printf( " Default value is %s" , decode(parameter.getDefaultValue()) );
            }
      
            w.println( '|' );
        }

    }

    /**
     * 
     * @param required
     * @param parameterList
     * @return
     */
    private List<Parameter> getParametersByRequired( boolean required, List<Parameter> parameterList )
    {
        List<Parameter> list = new ArrayList<Parameter>();

        for ( Iterator parameters = parameterList.iterator(); parameters.hasNext(); )
        {
            Parameter parameter = (Parameter) parameters.next();

            if ( parameter.isRequired() == required )
            {
                list.add( parameter );
            }
        }

        return list;
    }

}
