# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Deploy New Version

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: GPG Setup
        env:
          GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./gpg-setup.sh
      - name: Deploy to OSS Sonatype
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          OSS_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        # mvn -Prelease source:jar javadoc:jar deploy -Dgpg.passphrase=thephrase
        run: mvn -B -Prelease source:jar javadoc:jar deploy --file pom.xml -s settings-template.xml -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
